// Generated by Babel. Do not modify this. Modify listing.js and paste the output from Babel instead.
function _createForOfIteratorHelper(r, e) { var t = "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (!t) { if (Array.isArray(r) || (t = _unsupportedIterableToArray(r)) || e && r && "number" == typeof r.length) { t && (r = t); var _n = 0, F = function F() {}; return { s: F, n: function n() { return _n >= r.length ? { done: !0 } : { done: !1, value: r[_n++] }; }, e: function e(r) { throw r; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var o, a = !0, u = !1; return { s: function s() { t = t.call(r); }, n: function n() { var r = t.next(); return a = r.done, r; }, e: function e(r) { u = !0, o = r; }, f: function f() { try { a || null == t["return"] || t["return"](); } finally { if (u) throw o; } } }; }
function _unsupportedIterableToArray(r, a) { if (r) { if ("string" == typeof r) return _arrayLikeToArray(r, a); var t = {}.toString.call(r).slice(8, -1); return "Object" === t && r.constructor && (t = r.constructor.name), "Map" === t || "Set" === t ? Array.from(r) : "Arguments" === t || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t) ? _arrayLikeToArray(r, a) : void 0; } }
function _arrayLikeToArray(r, a) { (null == a || a > r.length) && (a = r.length); for (var e = 0, n = Array(a); e < a; e++) n[e] = r[e]; return n; }
var productList = {};
var typeObj = document.querySelector("#type");
var versionObj = document.querySelector("#version");
var editionObj = document.querySelector("#edition");
var downloadURL = document.querySelector("#download");
fetch("/downloads/products.json").then(function (data) {
  return data.json().then(function (products) {
    productList = products;
    // Normally we'd use constants, but Firefox <51 doesn't work right with the way we use them, so use variables.
    for (var i in products) {
      typeObj.append(new Option(i, i));
    }
  });
});
var updateVersions = function updateVersions() {
  var versionOptions = document.querySelectorAll("#version option");
  // ditto
  var _iterator = _createForOfIteratorHelper(versionOptions),
    _step;
  try {
    for (_iterator.s(); !(_step = _iterator.n()).done;) {
      var i = _step.value;
      if (!i.disabled) i.remove();
    }
  } catch (err) {
    _iterator.e(err);
  } finally {
    _iterator.f();
  }
  document.querySelector("#version option[value='placeholder']").selected = true;
  // ditto
  for (var i in productList[typeObj.value]) {
    versionObj.append(new Option(i, i));
  }
  updateEditions();
};
var updateEditions = function updateEditions() {
  var editionOptions = document.querySelectorAll("#edition option");
  var _iterator2 = _createForOfIteratorHelper(editionOptions),
    _step2;
  try {
    for (_iterator2.s(); !(_step2 = _iterator2.n()).done;) {
      var i = _step2.value;
      if (!i.disabled) i.remove();
    }
  } catch (err) {
    _iterator2.e(err);
  } finally {
    _iterator2.f();
  }
  document.querySelector("#edition option[value='placeholder']").selected = true;
  for (var i in productList[typeObj.value][versionObj.value]) {
    editionObj.append(new Option(i, i));
  }
  updateURL();
};
var updateURL = function updateURL() {
  if (typeObj.value && versionObj.value && editionObj.value) {
    var url = productList[typeObj.value][versionObj.value][editionObj.value];
    downloadURL.href = url;
  } else {
    downloadURL.removeAttr("href");
    downloadURL.disabled = true;
  }
};